title: Jane Shin
description: Personal academic homepage of Jane Shin, KAIST.
url: "https://JaneS1028.github.io"
baseurl: ""

lang: en
timezone: Asia/Seoul

social:
  name: Jane Shin
  email: janeshin@kaist.ac.kr
  links:
    - https://www.linkedin.com/in/jane-shin-9ba713218/

kramdown:
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
